---

- name: "Installation Apache"
  hosts: "front"
  gather_facts: no
  tasks:
    - name: "Installation package apache"
      package:
        name: "httpd"
        state: present
    - name: "Activer le service apache"
      service:
        name: "httpd"
        state: started
        enabled: yes
