---

- name: "Configure MariaDB"
  hosts: ["database"]
  gather_facts: no
  tasks:
    - name: "Install Python Plugin"
      package:
        name: "python-mysqldb"
        state: present

    - name: "Configure DB"
      mysql_db:
        name: "wordpress"
        state: present

    - name: "Create Wordpress user"
      mysql_user:
        name: "wordpress"
        password: "wordpress"
        priv: 'wordpress.*:ALL'
        state: present

    - name: "Set remote access to Wordpress user"
      mysql_user:
        name: "wordpress"
        host_all: yes
        state: present
