---

- name: "Configure MariaDB"
  hosts: ["database"]
  gather_facts: no
  tasks:
    - name: "Configure DB"
      mysql_db:
        name: "{{ wp_db_name }}"
        state: present

    - name: "Create Wordpress user"
      mysql_user:
        name: "{{ wp_db_username }}"
        password: "{{ wp_db_password }}"
        host: "{{ item }}.{{ domain_name }}"
        priv: '{{ wp_db_name }}.*:ALL'
        state: present
      loop: "{{ groups['front'] }}"
