---

- name: "Install Haproxy"
  hosts: ["lb"]
  gather_facts: no
  tasks:
    - name: "Install Haproxy"
      package:
        name: "haproxy"
        state: present

    - name: "Start Haproxy"
      service:
        name: "haproxy"
        enabled: yes
        state: started
