---

- name: "Install Haproxy"
  hosts: "lb"
  gather_facts: no
  handlers:
    - name: "Restart Haproxy"
      service:
        name: "haproxy"
        state: restarted
  tasks:
    - name: "Install Haproxy"
      apt:
        name: "haproxy"
        state: present

    - name: "Configuration Haproxy"
      template:
        src: "haproxy.cfg.j2"
        dest: "/etc/haproxy/haproxy.cfg"
      notify: "Restart Haproxy"

    - meta: flush_handlers

    - name: "Start Haproxy"
      service:
        name: "haproxy"
        enabled: yes
        state: started
