---

- name: "Install PHP 7"
  hosts: ["front"]
  gather_facts: no
  tasks:
    - name: "Install EPEL"
      package:
        name: "epel-release"
        state: present

    - name: "Install remi repo"
      package:
        name: "http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
        state: present

    - name: "Install PHP 7 from remi repo"
      package:
        name: "php"
        enablerepo: "remi-php73"
        state: present
