---

- name: "Install PHP 7"
  hosts: ["front"]
  gather_facts: no
  handlers:
    - name: "Restart Apache"
      service:
        name: "httpd"
        enabled: yes
        state: restarted
  tasks:
    - name: "Install EPEL"
      package:
        name: "epel-release"
        state: present
      notify: "Restart Apache"

    - name: "Install remi repo"
      package:
        name: "http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
        state: present
      notify: "Restart Apache"

    - name: "Install PHP 7 from remi repo"
      package:
        name: "php,php,php-mcrypt,php-gd,php-mysqlnd"
        enablerepo: "remi-php73"
        state: present
      notify: "Restart Apache"

    - name: "Install Apache"
      package:
        name: "httpd"
        state: present

    - name: "Start Apache"
      service:
        name: "httpd"
        enabled: yes
        state: started
