---

- name: "Install Python"
  hosts: ["database"]
  vars:
    ansible_connection: "docker"
  gather_facts: no
  tasks:
    - name: "Install Python"
      raw: apt update && apt install -y python
      args:
        creates: /usr/bin/python

- name: "Prepare host"
  hosts: ["front", "database"]
  vars:
    ansible_connection: "docker"
  gather_facts: yes
  gather_subset: "min"
  tasks:
    - name: "Install SSH"
      package:
        name: "openssh-server"
        state: present

    - name: "Start and enable SSH"
      service:
        name: "sshd"
        enabled: yes
        state: "started"
